export const links: Record<string, string> = {
    WebStorm: "https://www.jetbrains.com/de-de/webstorm/",
    vscode: "https://code.visualstudio.com/",
    PhpStorm: "https://www.jetbrains.com/de-de/phpstorm/",
    "Google Chrome": "https://www.google.com/chrome/",
    Rider: "https://www.jetbrains.com/de-de/rider/",
    DataGrip: "https://www.jetbrains.com/de-de/datagrip/",
    "Microsoft Teams": "https://www.microsoft.com/de-de/microsoft-teams/group-chat-software",
    Zoom: "https://zoom.us/",
    Canva: "https://www.canva.com/",
    "Font Awesome": "https://fontawesome.com/",
    Postman: "https://www.postman.com/",
    MacOS: "https://www.apple.com/de/macos",
    Hetzner: "https://www.hetzner.com/",
    PhpFriends: "https://php-friends.de/",
    Raidboxes: "https://raidboxes.io/",
    iTerm2: "https://iterm2.com/",
    Docker: "https://www.docker.com/",
    Joplin: "https://joplinapp.org/",
    Bitwarden: "https://bitwarden.com/",
    Jira: "https://www.atlassian.com/software/jira",
    Trello: "https://trello.com/",
    "Google Meet": "https://meet.google.com",
    "Oh My Zsh": "https://ohmyz.sh/",
    SIP: "https://sipapp.io/",
    "WooCommerce Subscriptions (WCS)":
        "https://woocommerce.com/de-de/products/woocommerce-subscriptions/",
    "WooCommerce (WC)": "https://woocommerce.com/",
    Elementor: "https://elementor.com/",
    ACF: "https://www.advancedcustomfields.com/",
    "WP Astra": "https://wpastra.com/",
    Vue: "https://vuejs.org/",
    SAPUI5: "https://sapui5.hana.ondemand.com/",
    OData: "https://www.odata.org/",
    "ASP.NET": "https://dotnet.microsoft.com/en-us/apps/aspnet",
    "Entity Framework": "https://learn.microsoft.com/de-de/ef/",
    "Geschützte Branches": "https://docs.github.com/articles/about-protected-branches",
    "Private Registry": "https://github.com/features/packages",
    Actions: "https://github.com/features/actions",
    Nginx: "https://nginx.org/",
    Apache2: "https://httpd.apache.org/",
    "Let's Encrypt": "https://letsencrypt.org/de/",
    Certbot: "https://certbot.eff.org/",
    ABAP: "https://help.sap.com/doc/abapdocu_751_index_htm/7.51/de-DE/abenabap_overview.htm",
    "PHP 8": "https://www.php.net/releases/8.0/",
    "Prepared Statements":
        "https://www.php.net/manual/en/mysqli.quickstart.prepared-statements.php",
    TypeScript: "https://www.typescriptlang.org/",
    Taxanomien: "https://kinsta.com/de/wissensdatenbank/was-ist-eine-taxonomie/",
    Markdown: "https://markdown.de/",
    Hooks: "https://developer.wordpress.org/plugins/hooks/",
    Shortcodes: "https://developer.wordpress.org/plugins/shortcodes/",
    Internationalization: "https://developer.wordpress.org/plugins/internationalization/",
    Filter: "https://developer.wordpress.org/plugins/hooks/filters/",
    "REST-API Endpunkte": "https://developer.wordpress.org/rest-api/",
    ES6: "https://www.w3schools.com/js/js_es6.asp",
    "SAP Fiori": "https://www.sap.com/germany/products/technology-platform/fiori.html",
    NPM: "https://www.npmjs.com/",
    Nuget: "https://www.nuget.org/",
    "SWAN GmbH": "https://www.swan.de/"
};
